name: Inventory Automation
main: com.github.SpectraFusion.InventoryAutomation.InventoryAutomation
version: 0.6.0
description: A variety of different functions for the inventory from automatic sorting of items to auto-replenishing of used items. ~More will be added in future releases~
author: SpectraFusion
commands:
    auto:
        description: Shows a list of all function statuses.
        usage: /auto
    auto sort:
        description: Sorts your player inventory.
        usage: /auto sort
    auto rep:
        description: Displays the current status of auto-replenishing.
        usage: /auto rep
    auto rep e:
        description: Enables auto-replenishing.
        usage: /auto rep e
    auto rep d:
        description: Disables auto-replenishing.
        usage: /auto rep d